### PR TITLE
Major changes commented, reset button added

### PR DESCRIPTION
**Pull request by QuartzShard**
I would recommend merging this, did mostly housekeeping.

### CODE REVIEW

**Comment by graveship** [comment]
I added classes to the Client which is better so we should go with the classes.

**Comment by QuartzShard** [comment]
Merge this first, then resolve the conflicts from classification

**Comment by vingard** [comment]
hey, i cant merge until the conflicts are solved and it wants me to use the command line, can you just manually commit the changes to the master branch?

**Comment by QuartzShard** [comment]
I'm trying to fix the conflcts but boy is it taking a while

**Comment by vingard** [comment]
ill sort them if u like, sorry we should of used a dev branch

**Comment by vingard** [comment]
it's probably best to just manually commit to master the changes conflicts are annoying

**Comment by QuartzShard** [comment]
nah nearly there
gotta love bash

**Comment by QuartzShard** [comment]
done

**Comment by graveship** [comment]
meer

**Pull request merged**
